language: node_js
sudo: true
node_js:
  - "0.10"
  - "4"
  - "5"

matrix:
  allow_failures:
   - node_js: "5"

addons:
  apt:
    packages:
      - dh-make
      - devscripts
      - debhelper
      - git
      - default-jdk
      - maven

services:
 - mongodb
 - rabbitmq

after_success:
 - ./extra/make-testcoveralls.sh

before_deploy:
 - ./extra/make-doc.sh
 - ./extra/make-deb.sh

deploy:
  provider: bintray
  file: .bintray.json
  user: $BINTRAY_USER
  key: $BINTRAY_KEY
  on:
    branch: travisfun 
    node: "0.10"

